# Laravel
alias sail="./vendor/bin/sail"
alias art="sail artisan"
alias migrate="sail artisan migrate"
alias rollback="art migrate:rollback"
alias df="dunit --filter"
# NPM
alias npmrw="npm run watch"
alias npmrd="npm run dev"
alias npmrp="npm run prod"
# Composer
alias composer="sail composer"
alias ci="composer install"
alias cupd="composer update"
alias cupg="composer upgrade"
alias cda="composer dump-autoload"
# Git
alias gs="git status"
alias ga="git add ."
alias gc="git commit"
alias gd="git diff master"
alias gb="git branch"
alias gpus="git pull"
alias gpul="git push"
# Misc
alias ba="sudo nano ~/.bash_aliases"
alias aliases="sudo nano ~/.bash_aliases"
alias updatealiases="source ~/.bash_aliases"
alias cls="clear"
alias src="cd ~/src"
alias code="cd ~/src"
alias ba="nano ~/.bash_aliases"
